netdata/learn

ingest.js
Still in testing.
This could be useful for anyone developing locally who wants to ingest documentation changes from a specific branch on their fork of the `netdata/netdata` repo. Only supports that repo for now.
=> Support passing username and branch to ingest script

docs/cloud/get-started.mdx, docs/cloud/spaces.md, sidebars.js
This is linked to this PR on the agent, since we can't change the path/directory structure on the agent the label on "Claim" is changed to "Connect to Cloud" but the file path still needs to remain as claim.
https://github.com/netdata/netdata/pull/11378
=> Fix on docs due to PR the agent around claiming review to connect

sidebars.js
As discussed in [Issue 11907](https://github.com/netdata/netdata/issues/11907#issuecomment-999003753).
=> Remove checks.plugin from sidebar, as it's an internal collector.

README.md, contribute/contribute.mdx, contribute/projects.mdx, docs/cheatsheet.mdx, docs/cloud.mdx, docs/cloud/beta-architecture/new-architecture.md, docs/cloud/get-started.mdx, docs/cloud/insights/metric-correlations.md, docs/cloud/manage/invite-your-team.md, docs/cloud/manage/sign-in.mdx, docs/cloud/manage/themes.md, docs/cloud/spaces.md, docs/cloud/visualize/dashboards.md, docs/cloud/visualize/interact-new-charts.md, docs/cloud/visualize/kubernetes.md, docs/cloud/visualize/nodes.md, docs/cloud/visualize/overview.md, docs/cloud/war-rooms.md, docs/docs.mdx
During the content audit, I've found 19 pages within the netdata/learn repository that had the following attribute in their frontmatter: 
```
custom_edit_URL: null
```
In turn, these pages didn't generate a "Edit this page" link at the bottom of each site which decreases the maintainability. 
I've added the respective source files in this PR.
=> Added custom_edit_URLs

netlify.toml
I modified the `netlify.toml` file to make sure links to our deleted pages redirect the user to a useful place.
Also cleaned up a daisy chain for FAQs.
I consulted with Austin on both changes.
=> Redirects for links to removed docs

netlify.toml
Cleaned up netlify.toml:
- removed a daisy chained redirect
- removed a non-functional redirect 
- Grouped contribute redirects
- Deleted a duplicate redirect
=> Clean up redirects

.github/workflows/check-broken-links.yml
Since the broken link checker doesn't really work at the moment, I disabled the automatic runs. 
We can still trigger the workflow manually.
In the mean time, we should be on the lookout for broken links in the netlify build log. Docusaurus has an in-built broken link checker.
=> Disable automatic BLC

README.md, src/components/OneLineInstall/index.js
This patch introduces a component called `OneLineInstallCurl`. 
The former `OneLineInstall` was renamed to `OneLineInstallWget`. 
This allows us to reuse the kickstart script and even add customization options.
=> Docs: Introducing customizable curl kickstart command

src/theme/DocItem/index.js
To improve the documentation feedback forms I added spambot catcher. 
However, we still need a field that captures the URL that a user submits feedback for. 
@novykh Any idea on where/ how to add that?
=> Improve docs feedback forms

sidebars.js
Add anomaly advisor under "Troubleshooting with Netdata Cloud". Similar to where metric correlations lives currently.
=> add Anomaly Advisor to sidebar

src/components/Collectors/_collector-components.jsx
When you supplement the URL to a collector config, it gets passed to `href={URL}` which is not the correct syntax to form a link. 
Add `"`
=> Fix href syntax

.github/workflows/check-broken-links-external.yml
Leaving the actual action but we will pause the scheduling and the issue creation to avoid flooding with "broken link" issues
=> Pause cron job of external link checker

sidebars.js
* PR #1072 added a new guide to query, so we include it in TOC tree
* `agent/libnetdata/simple_pattern` was added by mistake in the _get started_  section of the TOC tree, we archived it under the _Developers_ cat of the TOC tree
=> minor fix in toc tree 

src/theme/DocItem/index.js
Remove the _Need further help section_ from feedback forms && notify netlify for the honeypot field
=> Housekeeping for the forms

docusaurus.config.js
There is no point to have netdata.cloud on the navigation bar, let's change it to sign in to app.netdata.cloud
1. @lupimiguel is UTM ok? (just changed the learn from website)
=> Change learn navigation bar

docusaurus.config.js
we should use app.posthog.com since we now on posthog cloud.
=> update posthog endpoint

src/theme/NotFound.js
This will fire a "page-not-found" event each time a user hits the not found page in learn. 
Here is an example user i did this with: https://app.posthog.com/person/183d15d0923d8a-09b312e5bdee77-26021f51-15f900-183d15d09248dd#activeTab=events
We will be able to use this to easily get volume based list of 404's users are actually hitting each day/week and clean them up based on traffic.
=> swizzle not found to fire 'page-not-found' event

.github/workflows/check-broken-links.yml
Until https://github.com/orgs/netdata/projects/39/views/7 be investigated, we will snooze the notification. To check for broken links your either:
1. Go to the latest run of this action and check the logs
2. Check the netlify build logs (docusaurus has it's own internal broken link checker)
=> Snooze issue notifications about BLC

src/components/OneLineInstall/index.js, src/components/OneLineInstall/styles.module.css
Discussed in https://github.com/netdata/documentation/issues/22.
I added a fourth button to the component, that is unchecked, and upon checking it adds the parameters needed for claiming to the Cloud and to war rooms.
- In this I set the Codeblock to have by default text wrapping, so the user can see how the command will be affected by the checkboxes. 
If we instruct him to change stuff in the comment IMO it makes sense to show him the full command before he copies it. That being said, the Codeblock changing size as the user ticks stuff might be irritating, so use will tell if we revert back to having the whole box in one line
- <details><summary>I also fixed a bug of the OneLineInstallComponent</summary>
If you go to the Component that is now live, and click a page that has both the wget …
=> Update the OneLineInstall component to include a checkbox for Cloud claiming

README.md, src/components/OneLineInstall/index.js
i think we should have the claim part of the one line install widget just be as minimal as possible. 
this PR:
- removes the ROOM_ID stuff from the widget since you don't need it and its actually not that clear as a user how i would get my room id (we dont actually display it in All nodes in the app)
- links to claim docs in case user does not know what "claim" means.
end result is widget looks like this (only one thing to get and that's your claim token):
If we merge this then we can clean up the text marked with X in a follow on PR in netdata/netdata
=> remove room id's from one line install widget

src/components/Grid.js
Related to netdata/learn#1354
This new component requires the link to be inputted as: `[](LINK)` and then the ingest recognizes the link using a regular expression, and can replace it with the equivalent learn link.
=> Introduce BoxListItemRegexLink component

ingest/ingest.py
This PR adds the functionality to print a list of the broken links in the ingest process, with their temporary path, their custom_edit_url, and finally the URL itself, so one can bulk search for the URL and find where it is mentioned in a repository.
Along with this as discussed with @cakrit, it is intended that the ingest should fail upon detecting broken links, so this functionality has been added too, using the option `--fail-on-internal-broken-links` or `-f` for short.
By default failing on internal netdata broken links is disabled.
=> Add a check for netdata links that can't be converted during ingest

.github/workflows/ingest.yml
This PR bumps `peter-evans/create-pull-request` from `v3` to `v4`.
https://github.com/peter-evans/create-pull-request/blob/main/docs/updating.md#updating-from-v3-to-v4
=> Update ingest.yml to use newer version of `create-pull-request`

ingest/ingest.py
This is fairly straightforward, we dont need "sidebar_position" inside our `map.tsv` file, as it is simply the row of the entries in that file.
Essentially `sidebar_position` is `np.arange(1, len(mapDict)+1)`, where mapDict is `map.tsv`
=> Create sidebar_position inside the ingest script

static/api.html
Ahrefs reports that <https://learn.netdata.cloud/api> has no outgoing links, so let's test this with a "Back to Learn" button at the bottom of the file, it should be considered as an outgoing link, improving the page's score (and possibly searchability too)
=> Add a new button to the bottom of the API page to have an outgoing link

ingest/ingest.py
Pages having "`" in the link are reported as non-canonical pages. Backticks (`) should not be in the link or generated filename.
=> Remove backticks from generated filenames

ingest/ingest.py
Closes https://github.com/netdata/learn/issues/1542 which affects only the category "Monitor Anything". 
Normally all folders should have a category overview page, but the content inside "Monitor Anything" is vast, making it hard and impractical to have a category page for every single folder.
This PR sets a new rule for files going on ".../monitor-anything/..." in which a `slug: ` metadata is added.
This metadata allows us to change the link that the page appears on, and it is set with the same rules as the rest of Learn.
The code is edited in such a way to only change lines where needed, meaning that we should take account somewhere if a file has a slug metadata, then we should change an element and the rest of the functions should work normally.
So the edits are: …
=> Necessary changes for the monitor-anything category link fix

ingest/ingest.py
This is a redo of a reverted PR.
Related to https://github.com/netdata/learn/issues/1542 which affects only the category "Monitor Anything". 
Normally all folders should have a category overview page, but the content inside "Monitor Anything" is vast, making it hard and impractical to have a category page for every single folder.
This PR sets a new rule for files going on ".../monitor-anything/..." in which a `slug: ` metadata is added.
This metadata allows us to change the link that the page appears on, and it is set with the same rules as the rest of Learn.
The code is edited in such a way to only change lines where needed, meaning that we should take account somewhere if a file has a slug metadata, then we should change an element and the rest of the functions should work normally.
So …
=> [REDO] Necessary changes for the monitor-anything category link fix

ingest/ingest.py
This PR makes the ingest to not fail on missing files, as a restructure is currently underway, and the map file is being changed all the time, for now it will just display a warning message and the missing files.
=> Make ingest to not fail on missing files as restructure is underway

static/swagger-initializer.js
Hello,
Someone on the Discord server notified that learn.netdata.cloud/api was throwing an error and @ilyam8 forced me (help) to make a PR so here we are :-).
Default swagger URL changed when web/ folder got moved under src/ in main repo, related commit → https://github.com/netdata/netdata/commit/a75559dffe1beee48ce0942a86ad79fb7423c098
=> Fixed swagger default URL
