netdata/learn

docusaurus.config.js
package.json
yarn.lock

Adding PostHog plugin as per: https://github.com/PostHog/posthog-docusaurus
Tested it locally and i can see events being sent and see them in PostHog.

add posthog plugin

---

docs/cloud/get-started.mdx
docs/cloud/manage/sign-in.md

This PR is still not updated with the latest version of the "Verify email!" e-mail screenshot. Once that is available I'll update it.
Putting the PR to trigger the review

sign up to sign in CTA review

---

docs/cloud/get-started.mdx
docs/cloud/spaces.md
docs/cloud/visualize/interact-new-charts.md

Opening an initial PR for the first release of charts documentation.
There are still TO-DOs to capture images or GIFs, waiting on QA to progress a bit further before capturing those.
If you don't want to run this locally you can still see how using github rich-viewer option or using HackMD file I've put here https://hackmd.io/@DYemnA_wQ-2rvA2u6k3AQA/S1ItI6e4F
note: this documentation was done based on the existing one from here https://learn.netdata.cloud/docs/dashboard/interact-charts
P.S.: I'll need to do a PR on the Agent docs as well to place a similar disclaimer on the top of the page

Charts 2.0

---

src/data/News.js

Checked in with Jennifer to discuss changes. 
@DShreve2 There was no array in the News.js file to update the link to the new release notes. Where do we update that?

Updated News.js to include info from the new release

---

docs/cloud/data-privacy.mdx
sidebars.js

To promote the topic of data privacy in the Netdata Cloud, I added a topic and linked it into the navbar.

Added a privacy topic for Netdata Cloud for higher visibility.

---

src/pages/guides.js

During the content audit, I noticed some guides that weren't published on our guides homepage. To increase visibility, I added them.

Added missing guides

---

src/data/News.js

Updated our news section on learn.netdata.cloud to include the kickstart script update.

Added news about new kickstart script

---

src/components/OneLineInstall/index.js

I've updated the command for Linux installations. 
@Ferroin Please make sure it still works with the installation options or add the relevant installation options. 
P.S. Ideally we'll overhaul the whole documentation to a more interactive approach to getting the correct command. For now, we don't have to resources to make bigger changes, so we're starting small. @DShreve2

Updated the linux installation command

---

sidebars.js

Removed internal documentation about `libnetdata` after discussing the approach to internal docs with @vkalintiris.
Added Platform support policy document to the TOC.
-[ ] New TOC entry for `libnetdata/simple_pattern/README.md

Update Table of Contents

---

src/pages/guides.js

Add step 1 summary on guides page

---

docusaurus.config.js
package.json
yarn.lock

Solves https://github.com/netdata/learn/issues/958
The docusaurus docs say that you can add a string or an object to the [script parameter](https://docusaurus.io/docs/api/docusaurus-config#scripts). Therefore, I went ahead and added the autogenerated code as an object.

Add Smartlook tracking code

---

docs/cloud/insights/anomaly-advisor.md
docs/cloud/insights/anomaly-advisor.mdx
package.json
yarn.lock

Adding a video, and relocating the Note section to the end of the page.

Adding video to anomaly advisor learn page

---

docs/cloud/insights/anomaly-advisor.mdx

- add usage tips section
- get a better initial image

iteration of anomaly advisor docs

---

docs/cloud/visualize/interact-new-charts.md

Single and double clicks affect Play/Pause behavior only for action "Pan". The other actions have different behaviors. Added a line to explain that.

Qualify Play/Pause via chart clicks

---

docs/cloud/insights/metric-correlations.md

Goal is to avoid confusion with Anomaly Advisor also in place now.

Updated to remove references to anomaly

---

docs/cloud/spaces.md

Adding node obsoletion

---

docs/cloud.mdx
docs/cloud/data-privacy.mdx
docs/docs.mdx

Fix broken links

---

docs/cloud/visualize/overview.md

The docs were updated due to the work completed and being done on:
* [Feat]: Structure the composite chart bar in a way as if it was being explained in written English [#432](https://github.com/netdata/netdata-cloud/issues/432)
* [Feat]: Allow the definition of the aggregation function over time on composite charts bar [#433](https://github.com/netdata/netdata-cloud/issues/433
As from previous conversations, on the places where the intervention happened images were removed.
For further information on composite charts please refer to https://github.com/netdata/docs/blob/master/product/composite-charts/composite_charts_behind_the_scnenes.md

review of the composite char bar definition

---

src/pages/guides.js

I created a new category and added the netdata/netdata#13322 in it.
Closes #1080

include the new guide on a new category

---

docusaurus.config.js
package.json

We don't use smartlook anymore, so removed the dependencies and the lines in the config

remove smartlook from the code

---

yarn.lock

update browsers list

---

docs/cloud/visualize/nodes.md
docs/cloud/visualize/overview.md

In this PR I'm proposing changes to pages affected by the rework done on the Single Node view:
* https://learn.netdata.cloud/docs/cloud/visualize/overview
* https://learn.netdata.cloud/docs/cloud/visualize/nodes

review overview page and nodes page

---

docusaurus.config.js

revert navigation change, docs should be there

---

.github/workflows/ingest.yml
docs/agent/changelog.md
docs/agent/exporting/prometheus.md
docs/agent/packaging/installer.md
docs/agent/packaging/installer/methods/kickstart.md
docs/get-started.mdx
docs/store/change-metrics-storage.md
guides/export/export-netdata-metrics-graphite.md
guides/monitor/lamp-stack.md
guides/monitor/pi-hole-raspberry-pi.md
guides/step-by-step/step-00.md

Update node version for ingest.js

---

src/data/News.js

Quick update of the learn news

Update learn news

---

docusaurus.config.js

Check https://github.com/netdata/documentation/issues/21

Add the sign-in button CTA

---

ingest/ingest.py

rework GH to learn links

---

src/data/News.js

Update News.js for release 1.38

---

netlify.toml

following this: https://github.com/netdata/netdata/pull/14454
add some redirects to handle dead links

add some redirects

---

ingest/ingest.py

Closes #1346
This PR includes:
- The fix for a side effect mentioned in #1346
- A fix for multi line links not being detected by the regular expression
- A fix where a link to a file having an `id: "someId"` metadata doesn't get properly routed
- For this the signature of the `reductToPublishInGHLinksCorrelation` function needs to change, as we need to check the metadata that the file the URL links to has. Also the `learnPath` key-value pair should not be overwritten, but a new one should be made indicating the new location of the file. (In another cleanup PR these will need to be refactored, to keep things clean, at the moment this is a quality improvement for the linking strategy, so that's why I made only necessary changes to fix these issues.)

Improvements in the ingest script's link replacement logic

---

src/css/search.css

have search button color match navbar color on learn

Search button color

---

docusaurus.config.js

its more professional looking and standard practice

capitalise navbar words

---

netlify.toml

Only takes care of the `nightly` links now. We'll see how we'll handle the other links too.

Fix app redirects to nightly docs

---

src/theme/NotFound.js

404 page also replace "#" and "-" with " " in the search string

---

src/theme/SearchBar.js

This PR adds the placeholder on the SearchBar component upon loading it, resolving a bug where it wasn't rendering properly

Fix a bug in the Search bar

---

netlify.toml

Also moved them into the static section

Fix nightly redirects

---

map.tsv

Related to:
https://github.com/netdata/learn/issues/1384
https://github.com/netdata/netdata/pull/14653

Publish the Glossary

---

README.md

Related to https://github.com/netdata/learn/issues/1469
This PR updates the `README.md`, removing old sections, ensuring everything is up-to-date and checking spelling and syntax.

Update the information inside README.md

---

src/data/News.js
src/pages/index.js

WIP, changes are related to ahrefs issues

Homepage, change links from redirect links HTTP 301 to normal links

---

src/theme/MDXContent/index.js

Change CTAs at the bottom of each page

---

docusaurus.config.js

Change top level links in docusaurus.config.js

---

ingest/ingest.py

This PR closes https://github.com/netdata/learn/issues/1557
Assigns an integer to the `sidebar_position` metadata of each file following the rules:
1st level folders increment by 100000
2nd level folders increment by 2000
3rd level folders increment by 40
All other sub-folders increment by 1

Improve automated sidebar position 

---

docusaurus.config.js
src/css/custom.css

Under a width of 1440px the navbar behaves as our site navbar
Under a width of 996px (docusaurus's mobile cutoff point) the navbar has only the search and the logo becomes smaller.

Quality of life navbar fix

---

src/css/custom.css

@ilyam8 according to our discussion, please give your opinion on this style, I made `codeblocks` to be the same color with code box and their color white so it doesn't stand out all that much.

CSS improvements

---

src/components/OneLineInstall/index.js

This reverts commit 950767a3251e27c436d723763695c5a12908b1b0. 
This reverts commit 47f7dffe78b423fbb9b5b6305da1112a7cc77d3a.

Make again default channel nightly

---

ingest/ingest.py
map.tsv

This PR is to be merged without checks, it has been tested locally, and it works as expected, once merged an action should be run and it should finish successfully creating a big PR

Organize some docs and do some cleanup

---

ingest/ingest.py

The changes will not be reflected in this PR, the ingest needs to run first, it has been tested locally, so I will proceed with merging this and running the action.

Logic for having a link metadata

---

src/components/OneLineInstall/index.js

Relevant netdata/incidents#56
Docs change in netdata/netdata#16738

change get kickstart url to https://get.netdata.cloud/kickstart.sh

---

LegacyLearnCorrelateLinksWithGHURLs.json
map.tsv

Revert "move file"

---

ingest/ingest.py

This PR provides support for relative links from github docs.

relative link function

---

ingest/ingest.py

properly allocates space in-between categories

proper sidebar_position logic

---

ingest/ingest.py
map.tsv

changes to cover
https://github.com/netdata/infra/issues/5066
and 
https://github.com/netdata/netdata-cloud-onprem/pull/166

changes to ingest due to moved files

---

map.tsv

this was agreed by all involved parties.

Move on-prem category to top level, below Netdata Cloud

---

ingest/ingest.py
src/css/custom.css

used in [the getting started PR](https://github.com/netdata/netdata/pull/20642/files#diff-e8f7240ee1429fadec550e9733908b87289317ff700428d6feeb1553d375a464R13-R24), adds support for comments with tags in them, and a new class to not use `{{` which is replaced with `\{\{` by ingest to prevent MDX3 incompatibilities

new css class and logic in ingest

---

ingest/create_grid_integration_pages.py
map.tsv

To be merged after https://github.com/netdata/netdata/pull/20894

move exporting integrations to their own folder
